[alias]
wasm = "build --release --lib --target wasm32-unknown-unknown"
wasm-debug = "build --lib --target wasm32-unknown-unknown"
unit-test = "test --lib"
integration-test = "test --test integration"
schema = "run --bin schema"

[build]
rustflags = ["-C", "link-arg=-z", "-C", "link-arg=stack-size=8388608", "-C", "target-feature=-bulk-memory"]

[profile.release]
opt-level = 3
lto = false
